AWSTemplateFormatVersion: "2010-09-09"
Description: Create cross account role for service screener
Parameters:
  RoleName:
    Type: String
    Default: ServiceScreenerAssumeRole
  ExecutorArn:
    Type: String
Resources:
  SSRoleExternalID:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref RoleName
      MaxSessionDuration: 14400
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !Ref ExecutorArn
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/ReadOnlyAccess"
      Policies:
        - PolicyName: CloudFormationCreateStack
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "cloudformation:CreateStack"
                Resource: "*"
              - Effect: Allow
                Action: "cloudformation:DeleteStack"
                Resource: "arn:aws:cloudformation:*:*:stack/ssv2-*"
